repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.9
        exclude: |
          (?x)^(
              versioneer.py|
              docs/conf.py|
              lab_data_logger/_version.py
          )$
