repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
              versioneer.py|
              docs/conf.py|
              lab_data_logger/_version.py
          )$
